In [2]:
library(tidyverse)

── Attaching packages ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse 1.3.1 ──

✔ ggplot2 3.3.5     ✔ purrr   0.3.4
✔ tibble  3.1.2     ✔ dplyr   1.0.7
✔ tidyr   1.1.3     ✔ stringr 1.4.0
✔ readr   1.4.0     ✔ forcats 0.5.1

── Conflicts ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

In [13]:
df_meat <- read_csv("meat_consumption_worldwide.csv")
df_meat2 <- read_csv("DP_LIVE_19072021012255894.csv")

── Column specification ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
cols(
  LOCATION = col_character(),
  SUBJECT = col_character(),
  MEASURE = col_character(),
  TIME = col_double(),
  Value = col_double()
)



── Column specification ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
cols(
  LOCATION = col_character(),
  INDICATOR = col_character(),
  SUBJECT = col_character(),
  MEASURE = col_character(),
  FREQUENCY = col_character(),
  TIME = col_double(),
  Value = col_double(),
  `Flag Codes` = col_logical()
)

In [14]:
str(df_meat)
summary(df_meat)
head(df_meat)

str(df_meat2)
summary(df_meat2)
head(df_meat2)

spec_tbl_df [13,760 × 5] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
 $ LOCATION: chr [1:13760] "AUS" "AUS" "AUS" "AUS" ...
 $ SUBJECT : chr [1:13760] "BEEF" "BEEF" "BEEF" "BEEF" ...
 $ MEASURE : chr [1:13760] "KG_CAP" "KG_CAP" "KG_CAP" "KG_CAP" ...
 $ TIME    : num [1:13760] 1991 1992 1993 1994 1995 ...
 $ Value   : num [1:13760] 27.7 26.2 26.2 25.5 25.3 ...
 - attr(*, "spec")=
  .. cols(
  ..   LOCATION = col_character(),
  ..   SUBJECT = col_character(),
  ..   MEASURE = col_character(),
  ..   TIME = col_double(),
  ..   Value = col_double()
  .. )

   LOCATION           SUBJECT            MEASURE               TIME
 Length:13760       Length:13760       Length:13760       Min.   :1990
 Class :character   Class :character   Class :character   1st Qu.:1999
 Mode  :character   Mode  :character   Mode  :character   Median :2008
                                                          Mean   :2008
                                                          3rd Qu.:2017
                                                          Max.   :2026
     Value
 Min.   :     0.00
 1st Qu.:     3.48
 Median :    23.14
 Mean   :  1861.70
 3rd Qu.:   296.78
 Max.   :131607.31

  LOCATION SUBJECT MEASURE TIME Value
1 AUS      BEEF    KG_CAP  1991 27.72182
2 AUS      BEEF    KG_CAP  1992 26.19959
3 AUS      BEEF    KG_CAP  1993 26.16909
4 AUS      BEEF    KG_CAP  1994 25.45613
5 AUS      BEEF    KG_CAP  1995 25.34023
6 AUS      BEEF    KG_CAP  1996 27.25910

spec_tbl_df [12,160 × 8] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
 $ LOCATION  : chr [1:12160] "AUS" "AUS" "AUS" "AUS" ...
 $ INDICATOR : chr [1:12160] "MEATCONSUMP" "MEATCONSUMP" "MEATCONSUMP" "MEATCONSUMP" ...
 $ SUBJECT   : chr [1:12160] "BEEF" "BEEF" "BEEF" "BEEF" ...
 $ MEASURE   : chr [1:12160] "KG_CAP" "KG_CAP" "KG_CAP" "KG_CAP" ...
 $ FREQUENCY : chr [1:12160] "A" "A" "A" "A" ...
 $ TIME      : num [1:12160] 1990 1991 1992 1993 1994 ...
 $ Value     : num [1:12160] 0 27.9 26.4 26.4 25.7 ...
 $ Flag Codes: logi [1:12160] NA NA NA NA NA NA ...
 - attr(*, "spec")=
  .. cols(
  ..   LOCATION = col_character(),
  ..   INDICATOR = col_character(),
  ..   SUBJECT = col_character(),
  ..   MEASURE = col_character(),
  ..   FREQUENCY = col_character(),
  ..   TIME = col_double(),
  ..   Value = col_double(),
  ..   `Flag Codes` = col_logical()
  .. )

   LOCATION          INDICATOR           SUBJECT            MEASURE
 Length:12160       Length:12160       Length:12160       Length:12160
 Class :character   Class :character   Class :character   Class :character
 Mode  :character   Mode  :character   Mode  :character   Mode  :character



  FREQUENCY              TIME          Value           Flag Codes
 Length:12160       Min.   :1990   Min.   :     0.00   Mode:logical
 Class :character   1st Qu.:2000   1st Qu.:     5.45   NA's:12160
 Mode  :character   Median :2010   Median :    24.77
                    Mean   :2010   Mean   :  2291.58
                    3rd Qu.:2019   3rd Qu.:   433.10
                    Max.   :2029   Max.   :144874.23

  LOCATION INDICATOR   SUBJECT MEASURE FREQUENCY TIME Value  Flag Codes
1 AUS      MEATCONSUMP BEEF    KG_CAP  A         1990  0.000 NA
2 AUS      MEATCONSUMP BEEF    KG_CAP  A         1991 27.942 NA
3 AUS      MEATCONSUMP BEEF    KG_CAP  A         1992 26.405 NA
4 AUS      MEATCONSUMP BEEF    KG_CAP  A         1993 26.370 NA
5 AUS      MEATCONSUMP BEEF    KG_CAP  A         1994 25.662 NA
6 AUS      MEATCONSUMP BEEF    KG_CAP  A         1995 25.526 NA

In [8]:
df_meat %>% rename(YEAR = TIME, UNITS = MEASURE, MEAT = SUBJECT)

      LOCATION MEAT  UNITS      YEAR Value
1     AUS      BEEF  KG_CAP     1991 27.72182
2     AUS      BEEF  KG_CAP     1992 26.19959
3     AUS      BEEF  KG_CAP     1993 26.16909
4     AUS      BEEF  KG_CAP     1994 25.45613
5     AUS      BEEF  KG_CAP     1995 25.34023
6     AUS      BEEF  KG_CAP     1996 27.25910
7     AUS      BEEF  KG_CAP     1997 28.80291
8     AUS      BEEF  KG_CAP     1998 26.59048
9     AUS      BEEF  KG_CAP     1999 27.91828
10    AUS      BEEF  KG_CAP     2000 26.35462
11    AUS      BEEF  KG_CAP     2001 24.46036
12    AUS      BEEF  KG_CAP     2002 25.11619
13    AUS      BEEF  KG_CAP     2003 25.81171
14    AUS      BEEF  KG_CAP     2004 28.56664
15    AUS      BEEF  KG_CAP     2005 27.06127
16    AUS      BEEF  KG_CAP     2006 26.92517
17    AUS      BEEF  KG_CAP     2007 24.09762
18    AUS      BEEF  KG_CAP     2008 23.30106
19    AUS      BEEF  KG_CAP     2009 23.43242
20    AUS      BEEF  KG_CAP     2010 25.30049
21    AUS      BEEF  KG_CAP     2011 23.28277
22    AUS      BEEF  KG_CAP     2012 22.42724
23    AUS      BEEF  KG_CAP     2013 23.72833
24    AUS      BEEF  KG_CAP     2014 22.56231
25    AUS      BEEF  KG_CAP     2015 19.69922
26    AUS      BEEF  KG_CAP     2016 22.05103
27    AUS      BEEF  KG_CAP     2017 20.93937
28    AUS      BEEF  KG_CAP     2018 20.48333
29    AUS      BEEF  KG_CAP     2019 20.19778
30    AUS      BEEF  KG_CAP     2020 20.22747
⋮     ⋮        ⋮     ⋮          ⋮    ⋮
13731 MYS      SHEEP THND_TONNE 1997 13.00000
13732 MYS      SHEEP THND_TONNE 1998 14.00000
13733 MYS      SHEEP THND_TONNE 1999 14.00000
13734 MYS      SHEEP THND_TONNE 2000 14.00000
13735 MYS      SHEEP THND_TONNE 2001 17.00000
13736 MYS      SHEEP THND_TONNE 2002 15.00000
13737 MYS      SHEEP THND_TONNE 2003 13.00000
13738 MYS      SHEEP THND_TONNE 2004 15.00000
13739 MYS      SHEEP THND_TONNE 2005 16.00000
13740 MYS      SHEEP THND_TONNE 2006 18.00000
13741 MYS      SHEEP THND_TONNE 2007 20.00000
13742 MYS      SHEEP THND_TONNE 2008 20.00000
13743 MYS      SHEEP THND_TONNE 2009 20.00000
13744 MYS      SHEEP THND_TONNE 2010 24.00000
13745 MYS      SHEEP THND_TONNE 2011 20.00000
13746 MYS      SHEEP THND_TONNE 2012 22.00000
13747 MYS      SHEEP THND_TONNE 2013 27.00000
13748 MYS      SHEEP THND_TONNE 2014 33.00000
13749 MYS      SHEEP THND_TONNE 2015 36.00000
13750 MYS      SHEEP THND_TONNE 2016 40.00000
13751 MYS      SHEEP THND_TONNE 2017 40.61234
13752 MYS      SHEEP THND_TONNE 2018 41.37322
13753 MYS      SHEEP THND_TONNE 2019 42.04276
13754 MYS      SHEEP THND_TONNE 2020 42.69519
13755 MYS      SHEEP THND_TONNE 2021 43.41279
13756 MYS      SHEEP THND_TONNE 2022 44.15415
13757 MYS      SHEEP THND_TONNE 2023 44.89759
13758 MYS      SHEEP THND_TONNE 2024 45.61211
13759 MYS      SHEEP THND_TONNE 2025 46.32531
13760 MYS      SHEEP THND_TONNE 2026 47.04721

In [16]:
df_meat %>% select(LOCATION) %>% unique()

   LOCATION
1  AUS
2  CAN
3  JPN
4  KOR
5  MEX
6  NZL
7  TUR
8  USA
9  DZA
10 ARG
11 BGD
12 BRA
13 CHL
14 CHN
15 COL
16 EGY
17 ETH
18 GHA
19 HTI
20 IND
21 IDN
22 IRN
23 ISR
24 KAZ
25 MYS
26 MOZ
27 NGA
28 PAK
29 PRY
30 PER
31 PHL
32 RUS
33 SAU
34 ZAF
35 SDN
36 TZA
37 THA
38 UKR
39 URY
40 VNM
41 ZMB
42 WLD
43 SSA
44 OECD
45 BRICS
46 EU28
47 NOR
48 CHE